export const cars = [
    {
        id: 1,
        brand: "Mercedes-Benz",
        model: "C63",
        productionYear: 2003,
        type: "COUPE",
        price: 300,
        image: "c63.jpg",
        location: "Strumica, Address 1",
        fuelType: "Petrol",
    },
    {
        id: 2,
        brand: "BMW",
        model: "M3",
        productionYear: 2019,
        type: "SEDAN",
        price: 400,
        image: "m3.jpg",
        location: "Skopje, Address 2",
        fuelType: "Petrol",
    },
    {
        id: 3,
        brand: "Audi",
        model: "RS5",
        productionYear: 2018,
        type: "COUPE",
        price: 300,
        image: "rs5.jpg",
        location: "Bitola, Address 3",
        fuelType: "Petrol",
    },
    {
        id: 4,
        brand: "Volkswagen",
        model: "Golf R",
        productionYear: 2022,
        type: "HATCHBACK",
        price: 200,
        image: "golf.jpg",
        location: "Skopje, Address 4",
        fuelType: "Petrol",
    },
    {
        id: 5,
        brand: "Toyota",
        model: "Supra",
        productionYear: 2021,
        type: "COUPE",
        price: 300,
        image: "supra.jpg",
        location: "Ohrid, Address 5",
        fuelType: "Petrol",
    },
    {
        id: 6,
        brand: "Porsche",
        model: "911 Turbo S",
        productionYear: 2023,
        type: "COUPE",
        price: 400,
        image: "911.jpg",
        location: "Skopje, Address 6",
        fuelType: "Petrol",
    },
    {
        id: 7,
        brand: "Ford",
        model: "Mustang GT",
        productionYear: 2020,
        type: "COUPE",
        price: 350,
        image: "mustang.jpg",
        location: "Bitola, Address 7",
        fuelType: "Petrol",
    },
    {
        id: 8,
        brand: "Lamborghini",
        model: "Huracan",
        productionYear: 2022,
        type: "COUPE",
        price: 500,
        image: "huracan.jpg",
        location: "Ohrid, Address 8",
        fuelType: "Petrol",
    },
    {
        id: 9,
        brand: "Ferrari",
        model: "F8 Tributo",
        productionYear: 2024,
        type: "COUPE",
        price: 500,
        image: "f8.jpg",
        location: "Tetovo, Address 9",
        fuelType: "Petrol",
    },
    {
        id: 10,
        brand: "Nissan",
        model: "GT-R",
        productionYear: 2018,
        type: "COUPE",
        price: 450,
        image: "gtr.jpg",
        location: "Kumanovo, Address 10",
        fuelType: "Petrol",
    },
    {
        id: 11,
        brand: "Honda",
        model: "Accord",
        productionYear: 2021,
        type: "SEDAN",
        price: 350,
        image: "accord.jpg",
        location: "Skopje, Address 11",
        fuelType: "Petrol",
    },
    {
        id: 12,
        brand: "Hyundai",
        model: "Sonata",
        productionYear: 2022,
        type: "SEDAN",
        price: 300,
        image: "sonata.jpg",
        location: "Bitola, Address 12",
        fuelType: "Hybrid",
    },
    {
        id: 13,
        brand: "Toyota",
        model: "Camry",
        productionYear: 2023,
        type: "SEDAN",
        price: 400,
        image: "camry.jpg",
        location: "Ohrid, Address 13",
        fuelType: "Hybrid",
    },
    {
        id: 14,
        brand: "BMW",
        model: "5 Series",
        productionYear: 2020,
        type: "SEDAN",
        price: 450,
        image: "5series.jpg",
        location: "Skopje, Address 14",
        fuelType: "Diesel",
    },
    {
        id: 15,
        brand: "Audi",
        model: "A6",
        productionYear: 2021,
        type: "SEDAN",
        price: 500,
        image: "a6.jpg",
        location: "Prilep, Address 15",
        fuelType: "Diesel",
    },
    {
        id: 16,
        brand: "Jeep",
        model: "Grand Cherokee",
        productionYear: 2022,
        type: "SUV",
        price: 450,
        image: "grandcherokee.jpg",
        location: "Skopje, Address 16",
        fuelType: "Diesel",
    },
    {
        id: 17,
        brand: "Range Rover",
        model: "Velar",
        productionYear: 2021,
        type: "SUV",
        price: 600,
        image: "velar.jpg",
        location: "Strumica, Address 17",
        fuelType: "Diesel",
    },
    {
        id: 18,
        brand: "BMW",
        model: "X5",
        productionYear: 2023,
        type: "SUV",
        price: 700,
        image: "x5.jpg",
        location: "Skopje, Address 18",
        fuelType: "Diesel",
    },
    {
        id: 19,
        brand: "Mercedes-Benz",
        model: "GLC",
        productionYear: 2022,
        type: "SUV",
        price: 650,
        image: "glc.jpg",
        location: "Bitola, Address 19",
        fuelType: "Diesel",
    },
    {
        id: 20,
        brand: "Toyota",
        model: "Land Cruiser",
        productionYear: 2025,
        type: "SUV",
        price: 750,
        image: "landcruiser.jpg",
        location: "Strumica, Address 20",
        fuelType: "Diesel",
    },
    {
        id: 21,
        brand: "Volkswagen",
        model: "Polo",
        productionYear: 2021,
        type: "HATCHBACK",
        price: 180,
        image: "polo.jpg",
        location: "Gevgelija, Address 21",
        fuelType: "Petrol",
    },
    {
        id: 22,
        brand: "Honda",
        model: "Civic",
        productionYear: 2020,
        type: "HATCHBACK",
        price: 250,
        image: "civic.jpg",
        location: "Bitola, Address 22",
        fuelType: "Petrol",
    },
    {
        id: 23,
        brand: "Ford",
        model: "Focus ST",
        productionYear: 2022,
        type: "HATCHBACK",
        price: 280,
        image: "focus.jpg",
        location: "Ohrid, Address 23",
        fuelType: "Petrol",
    },
    {
        id: 24,
        brand: "Mazda",
        model: "3",
        productionYear: 2021,
        type: "HATCHBACK",
        price: 220,
        image: "mazda3.jpg",
        location: "Gostivar, Address 24",
        fuelType: "Petrol",
    },
    {
        id: 25,
        brand: "BMW",
        model: "1 Series",
        productionYear: 2023,
        type: "HATCHBACK",
        price: 350,
        image: "bmw1.jpg",
        location: "Strumica, Address 25",
        fuelType: "Diesel",
    }
    ];
